"use strict";

const browserGlobals = {
  ArrayBuffer: "readonly",
  Blob: "readonly",
  CSS: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  crypto: "readonly",
  DOMException: "readonly",
  Event: "readonly",
  File: "readonly",
  FileReader: "readonly",
  fetch: "readonly",
  HTMLCanvasElement: "readonly",
  ImageData: "readonly",
  MessageEvent: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  Uint8Array: "readonly",
  Uint8ClampedArray: "readonly",
  Worker: "readonly",
  document: "readonly",
  globalThis: "readonly",
  importScripts: "readonly",
  module: "readonly",
  navigator: "readonly",
  performance: "readonly",
  requestAnimationFrame: "readonly",
  require: "readonly",
  setTimeout: "readonly",
  self: "readonly",
  window: "readonly",
};

const nodeGlobals = {
  Buffer: "readonly",
  URL: "readonly",
  __dirname: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  module: "readonly",
  process: "readonly",
  require: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
};

module.exports = [
  {
    ignores: ["coverage/**", "node_modules/**", "playwright-report/**", "test-results/**"],
  },
  {
    files: [
      "tools/animation_tuner/public/watermark_studio.js",
      "tools/animation_tuner/public/watermark_smart_controls.js",
    ],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: browserGlobals,
    },
    rules: {
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrors: "none" }],
    },
  },
  {
    files: ["tools/animation_tuner/watermark_studio/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: nodeGlobals,
    },
    rules: {
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrors: "none" }],
    },
  },
  {
    files: [
      "tools/animation_tuner/public/batch_cutout_*core.js",
      "tools/animation_tuner/public/batch_cutout_queue.js",
      "tools/animation_tuner/public/batch_cutout_preview.js",
      "tools/animation_tuner/public/batch_cutout_protection_preview.js",
      "tools/animation_tuner/public/batch_cutout_gesture_controller.js",
      "tools/animation_tuner/public/batch_cutout_text.js",
      "tools/animation_tuner/public/batch_cutout_image_controller.js",
      "tools/animation_tuner/public/batch_cutout_preview_renderer.js",
      "tools/animation_tuner/public/batch_cutout_ui_controller.js",
      "tools/animation_tuner/public/batch_cutout_repair_controller.js",
      "tools/animation_tuner/public/batch_cutout_process_controller.js",
      "tools/animation_tuner/public/batch_cutout_session_controller.js",
      "tools/animation_tuner/public/batch_cutout_events.js",
      "tools/animation_tuner/public/batch_cutout_events_preview.js",
      "tools/animation_tuner/public/batch_cutout_navigation.js",
      "tools/animation_tuner/public/batch_cutout_processing_helpers.js",
      "tools/animation_tuner/public/batch_cutout_settings.js",
      "tools/animation_tuner/public/batch_cutout_reference_input.js",
      "tools/animation_tuner/public/batch_cutout_runtime_setup.js",
      "tools/animation_tuner/public/batch_cutout_worker*.js",
      "tools/animation_tuner/public/cutout_*core.js",
      "tools/animation_tuner/public/frame_organizer*.js",
      "tools/animation_tuner/public/character_starter_guide.js",
      "tools/animation_tuner/public/local_media_export_client.js",
      "tools/animation_tuner/public/media_export_core.js",
      "tools/animation_tuner/public/media_export_dialog.js",
      "tools/animation_tuner/public/app_filmstrip.js",
      "tools/animation_tuner/public/app_filmstrip_interaction.js",
      "tools/animation_tuner/public/app_attachment_sequence.js",
      "tools/animation_tuner/public/app_attachments.js",
      "tools/animation_tuner/public/app_stage_view.js",
      "tools/animation_tuner/public/app_keyboard.js",
      "tools/animation_tuner/public/app_transform_runtime.js",
      "tools/animation_tuner/public/app_box_adjustment.js",
      "tools/animation_tuner/public/app_adjustment_inputs.js",
      "tools/animation_tuner/public/app_attachment_manipulation.js",
      "tools/animation_tuner/public/app_attack_trail_mapping.js",
      "tools/animation_tuner/public/app_playback_inputs.js",
      "tools/animation_tuner/public/app_project_selects.js",
      "tools/animation_tuner/public/godot_handoff_controller.js",
      "tools/animation_tuner/public/app_frame_edit_state.js",
      "tools/animation_tuner/public/app_tool_actions.js",
      "tools/animation_tuner/public/app_composite_context.js",
      "tools/animation_tuner/public/app_canvas_renderer_layers.js",
      "tools/animation_tuner/public/app_canvas_renderer.js",
      "tools/animation_tuner/public/app_project_lifecycle.js",
      "tools/animation_tuner/public/app_project_state.js",
      "tools/animation_tuner/public/app_events_input_helpers.js",
      "tools/animation_tuner/public/app_events_stage_pointer.js",
      "tools/animation_tuner/public/app_events.js",
      "tools/animation_tuner/public/app_tuning_values.js",
      "tools/animation_tuner/public/app_save_controller.js",
      "tools/animation_tuner/public/scatter_slice*.js",
    ],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "script",
      globals: browserGlobals,
    },
    rules: {
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrors: "none" }],
    },
  },
  {
    files: [
      "tools/animation_tuner/server_io_worker.js",
      "tools/animation_tuner/server_io_operations.js",
      "tools/animation_tuner/server_http.js",
      "tools/animation_tuner/server_project_persistence.js",
      "tools/animation_tuner/server_project_save.js",
      "tools/animation_tuner/server_project_validation.js",
      "tools/animation_tuner/server_project_view.js",
      "tools/animation_tuner/server_project_routes.js",
      "tools/animation_tuner/server_media_routes.js",
      "tools/animation_tuner/server_media_export.js",
      "tools/animation_tuner/server_static.js",
      "tools/animation_tuner/server_validation.js",
      "tools/animation_tuner/server_watermark_studio.js",
      "tools/animation_mutations.js",
      "tools/attachment_alignment_core.js",
      "tools/auto_align_attachments.js",
      "tools/frame_organizer.js",
      "tools/framepacker_perf_baseline.js",
      "tools/project_store.js",
      "tools/quality_gate.js",
      "tools/self_test_frame_organizer_core.js",
      "tools/self_test_cutout_core.js",
      "tools/self_test_cutout_product.js",
      "tools/self_test_cutout_product_basic.js",
      "tools/self_test_cutout_product_golden.js",
      "tools/self_test_cutout_product_reference.js",
      "tools/self_test_cutout_protection.js",
      "tools/self_test_cutout_tracking.js",
      "tools/self_test_server_integration.js",
    ],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "commonjs",
      globals: nodeGlobals,
    },
    rules: {
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrors: "none" }],
    },
  },
];
