"use strict";

const zlib = require("node:zlib");

/**
 * Reads ZIP entries generated by the browser without adding a ZIP test dependency.
 *
 * The application exporter writes local headers with known sizes and uses either
 * stored or deflated entry data. Unsupported ZIP features fail loudly so tests do
 * not silently accept an unreadable archive.
 *
 * @param {Buffer} archive ZIP archive bytes.
 * @returns {Map<string, Buffer>} Uncompressed entry contents by file name.
 */
function readZipEntries(archive) {
  if (!Buffer.isBuffer(archive)) throw new TypeError("ZIP archive must be a Buffer");

  const entries = new Map();
  let offset = 0;
  while (offset + 30 <= archive.length && archive.readUInt32LE(offset) === 0x04034b50) {
    const flags = archive.readUInt16LE(offset + 6);
    const method = archive.readUInt16LE(offset + 8);
    const compressedSize = archive.readUInt32LE(offset + 18);
    const nameLength = archive.readUInt16LE(offset + 26);
    const extraLength = archive.readUInt16LE(offset + 28);
    if (flags & 0x08) throw new Error("ZIP data descriptors are not supported by this test reader");
    if (method !== 0 && method !== 8) throw new Error(`Unsupported ZIP compression method: ${method}`);

    const nameStart = offset + 30;
    const dataStart = nameStart + nameLength + extraLength;
    const dataEnd = dataStart + compressedSize;
    if (dataEnd > archive.length) throw new Error("ZIP entry extends beyond archive bounds");

    const name = archive.subarray(nameStart, nameStart + nameLength).toString("utf8");
    const compressed = archive.subarray(dataStart, dataEnd);
    entries.set(name, method === 8 ? zlib.inflateRawSync(compressed) : Buffer.from(compressed));
    offset = dataEnd;
  }
  return entries;
}

module.exports = { readZipEntries };
