"use strict";

/**
 * Declarative catalog of the XSXB MCP tools: the advertised order, the input
 * schema of every tool, and the annotations clients use to reason about them.
 * Kept apart from the service so the schemas can be read and reviewed without
 * scrolling past the handler implementations.
 */

const path = require("node:path");
const { ORGANIZER_SIMILARITY_THRESHOLD } = require("./animation_tuner/public/frame_organizer_core");
const { workbenchSliderSchemaProperties } = require("./xsxb_mcp_cutout");
const { WORKFLOW_NAMES } = require("./xsxb_mcp_workflows");

const DEFAULT_PROFILE_ID = "mcp_imports";
const OUTPUT_PRIMARY_FIELDS = Object.freeze({
  xsxb_list_projects: ["count", "number"],
  xsxb_create_project: ["projectId", "string"],
  xsxb_get_project: ["projectId", "string"],
  xsxb_get_workflow: ["workflow", "string"],
  xsxb_import_video: ["importedFrameCount", "number"],
  xsxb_import_animation: ["importedFrameCount", "number"],
  xsxb_get_animation: ["frameCount", "number"],
  xsxb_find_loop: ["candidates", "array"],
  xsxb_find_duplicates: ["order", "array"],
  xsxb_find_motion: ["order", "array"],
  xsxb_update_frame_boxes: ["projectId", "string"],
  xsxb_estimate_boxes: ["estimatedFrames", "number"],
  xsxb_update_timing: ["fps", "number"],
  xsxb_set_visual_transform: ["level", "string"],
  xsxb_estimate_visual: ["projectId", "string"],
  xsxb_reorganize_frames: ["outputFrameCount", "number"],
  xsxb_replace_frame: ["frame", "number"],
  xsxb_add_attack_trail: ["bindingKey", "string"],
  xsxb_plan_attachment: ["plan", "object"],
  xsxb_add_attachment: ["bindingCount", "number"],
  xsxb_add_sfx: ["bindingCount", "number"],
  xsxb_remove_binding: ["removedCount", "number"],
  xsxb_delete_animation: ["deleted", "boolean"],
  xsxb_list_project_revisions: ["count", "number"],
  xsxb_restore_project_revision: ["status", "string"],
  xsxb_sync_godot: ["requested", "boolean"],
  xsxb_validate_project: ["ok", "boolean"],
  xsxb_set_active_project: ["activeProjectId", "string"],
  xsxb_bind_godot: ["projectId", "string"],
  xsxb_cutout: ["processedFrameCount", "number"],
  xsxb_export_gif: ["outputPath", "string"],
  xsxb_export_sheet: ["outputPath", "string"],
  xsxb_measure_image: ["filePath", "string"],
  xsxb_open_tuner: ["url", "string"],
});
const COMMON_OUTPUT_FIELDS = Object.freeze([
  "projectId",
  "profileId",
  "animationId",
  "status",
  "warnings",
  "sync",
  "validation",
  "dryRun",
  "mutationJournalStatus",
  "mutationRevisionId",
  "mutationBeforeRevision",
  "mutationAfterRevision",
  "reviewArtifactId",
  "reviewArtifactHash",
  "reviewArtifactUri",
  "reviewPolicy",
  "requiredCapabilities",
  "fallback",
  "canAutoApplyWithoutVision",
]);
const OUTPUT_FIELDS = Object.freeze({
  xsxb_list_projects: ["activeProjectId", "count", "projects"],
  xsxb_create_project: ["projectId", "created", "dryRun", "activeProjectId", "project"],
  xsxb_get_project: [
    "id",
    "label",
    "kind",
    "projectRoot",
    "petRoot",
    "dataDir",
    "workspaceDir",
    "dataPath",
    "workspacePath",
    "projectId",
    "active",
    "godotProjectValid",
    "godotProjectRoot",
    "profileCount",
    "animationCount",
    "frameCount",
    "profiles",
    "animations",
    "sync",
  ],
  xsxb_get_workflow: [
    "workflow",
    "preconditions",
    "steps",
    "completionChecks",
    "requiredCapabilities",
    "fallback",
    "canAutoApplyWithoutVision",
    "failureFeedback",
  ],
  xsxb_import_video: [
    "source",
    "projectId",
    "profileId",
    "animationId",
    "sourceVideo",
    "fps",
    "extractedFrameCount",
    "importedFrameCount",
    "startFrame",
    "endFrame",
    "replaced",
    "targetDirectory",
    "sync",
    "validation",
  ],
  xsxb_import_animation: [
    "source",
    "projectId",
    "profileId",
    "animationId",
    "fps",
    "sourceVideo",
    "extractedFrameCount",
    "importedFrameCount",
    "importedAnimationCount",
    "animations",
    "startFrame",
    "endFrame",
    "sourceFrameCount",
    "replaced",
    "targetDirectory",
    "sync",
    "validation",
  ],
  xsxb_get_animation: [
    "project",
    "profile",
    "animation",
    "frameCount",
    "generatedFrameCount",
    "allFramesGenerated",
    "boxes",
    "timing",
    "visual",
    "sfx",
    "attachments",
    "trails",
    "summary",
    "sampleFrames",
  ],
  xsxb_find_loop: [
    "source",
    "applied",
    "projectId",
    "profileId",
    "animationId",
    "frameCount",
    "sampleSize",
    "candidates",
    "recommended",
    "oneShotLikely",
    "note",
  ],
  xsxb_find_duplicates: [
    "source",
    "applied",
    "projectId",
    "profileId",
    "animationId",
    "frameCount",
    "sampleSize",
    "threshold",
    "requestedThreshold",
    "effectiveThreshold",
    "autoAdjustedThreshold",
    "suggestedOrder",
    "suggestedDrop",
    "dropIndexes",
    "drop",
    "order",
    "comparisons",
    "matches",
    "groups",
    "note",
  ],
  xsxb_find_motion: [
    "source",
    "applied",
    "projectId",
    "profileId",
    "animationId",
    "frameCount",
    "preset",
    "rawStart",
    "rawEnd",
    "start",
    "end",
    "order",
    "paddingBefore",
    "paddingAfter",
    "opaqueRatio",
    "analysisReliable",
    "warnings",
    "activity",
    "semanticProvenance",
    "semanticFrames",
    "semanticCacheReused",
    "frames",
  ],
  xsxb_update_frame_boxes: [
    "projectId",
    "profileId",
    "animationId",
    "updatedFrames",
    "frame",
    "key",
    "boxes",
    "updates",
    "sync",
  ],
  xsxb_estimate_boxes: [
    "projectId",
    "profileId",
    "animationId",
    "frameCount",
    "estimatedFrames",
    "skippedExistingFrames",
    "replace",
    "dryRun",
    "sourceAttachmentId",
    "attachmentHitboxFrames",
    "semanticProvenance",
    "semanticFrames",
    "semanticCacheReused",
    "frames",
    "sync",
  ],
  xsxb_update_timing: ["projectId", "profileId", "animationId", "fps", "playback", "playbackUpdates", "sync"],
  xsxb_set_visual_transform: [
    "projectId",
    "profileId",
    "animationId",
    "level",
    "base",
    "values",
    "frame",
    "key",
    "override",
    "cleared",
    "sync",
  ],
  xsxb_estimate_visual: [
    "projectId",
    "profileId",
    "animationId",
    "referenceAnimationId",
    "targetHeight",
    "nativeHeight",
    "groupScale",
    "zoomRatio",
    "applied",
    "zoomFrameCount",
    "frames",
    "sync",
  ],
  xsxb_reorganize_frames: [
    "projectId",
    "profileId",
    "animationId",
    "inputFrameCount",
    "outputFrameCount",
    "order",
    "identityOrder",
    "fps",
    "targetDirectory",
    "sync",
  ],
  xsxb_replace_frame: [
    "projectId",
    "profileId",
    "animationId",
    "frame",
    "path",
    "previousSize",
    "newSize",
    "sizeChanged",
    "warnings",
    "sync",
  ],
  xsxb_add_attack_trail: [
    "projectId",
    "dryRun",
    "applied",
    "bindingKey",
    "segment",
    "frameSpan",
    "centerTravel",
    "edgeTravel",
    "note",
    "sourceAttachmentId",
    "derivedStickCount",
    "bladeWidthScale",
    "sourceFxOverlapRatio",
    "sourceFxFrames",
    "warnings",
    "sync",
  ],
  xsxb_plan_attachment: [
    "projectId",
    "profileId",
    "animationId",
    "planId",
    "planSchemaVersion",
    "responseMode",
    "plan",
    "previewPath",
    "frameCount",
    "requiresVisualReview",
    "reviewArtifactId",
    "reviewArtifactHash",
    "reviewPolicy",
    "gripErrorPx",
    "tipAngleErrorDeg",
  ],
  xsxb_add_attachment: [
    "projectId",
    "planId",
    "status",
    "updatedFrames",
    "bindings",
    "binding",
    "bindingCount",
    "requiresVisualReview",
    "previewPath",
    "gripErrorPx",
    "tipAngleErrorDeg",
    "validation",
    "backups",
    "revision",
    "warnings",
    "reviewArtifactId",
    "reviewArtifactHash",
    "syncPending",
    "sync",
  ],
  xsxb_add_sfx: ["projectId", "binding", "bindingCount", "sync"],
  xsxb_remove_binding: [
    "projectId",
    "profileId",
    "animationId",
    "kind",
    "id",
    "frame",
    "dryRun",
    "removed",
    "removedCount",
    "remainingCount",
    "sync",
  ],
  xsxb_delete_animation: [
    "projectId",
    "profileId",
    "animationId",
    "removedFrames",
    "removedDirectory",
    "dryRun",
    "deleted",
    "sync",
  ],
  xsxb_list_project_revisions: ["projectId", "count", "revisions"],
  xsxb_restore_project_revision: [
    "projectId",
    "revisionId",
    "dryRun",
    "status",
    "restoreToken",
    "files",
    "beforeRevision",
    "currentRevision",
    "restoredFiles",
    "revision",
    "sync",
  ],
  xsxb_sync_godot: [
    "projectId",
    "force",
    "dryRun",
    "includedAnimationIds",
    "availableAnimationIds",
    "animations",
    "requested",
    "ok",
    "reason",
    "projectRoot",
    "dataDir",
    "assetRoot",
    "copiedFrames",
    "frameCount",
    "prunedFrameFiles",
    "wroteTuning",
    "audioCount",
    "copiedAudio",
    "imageAttachmentCount",
    "copiedImageAttachments",
    "attackTrailCount",
    "copiedAttackTrailTextures",
    "wroteRuntime",
    "runtimeFiles",
  ],
  xsxb_validate_project: [
    "ok",
    "errors",
    "warnings",
    "summary",
    "strict",
    "layer",
    "layers",
    "gameplayReady",
    "nonBlockingWarnings",
  ],
  xsxb_set_active_project: ["activeProjectId", "project"],
  xsxb_bind_godot: ["projectId", "projectRoot", "previousRoot", "godotProjectValid"],
  xsxb_cutout: [
    "projectId",
    "profileId",
    "animationId",
    "pipeline",
    "rematched",
    "rematchMode",
    "frameScales",
    "keyed",
    "backgroundColor",
    "keyColor",
    "outputWidth",
    "outputHeight",
    "frameCount",
    "processedFrameCount",
    "skippedFrameCount",
    "boxesStale",
    "staleBoxFrameCount",
    "boxesReestimated",
    "metrics",
    "metricsSource",
    "sync",
  ],
  xsxb_export_gif: [
    "projectId",
    "profileId",
    "animationId",
    "outputPath",
    "frameCount",
    "skippedDisabledFrames",
    "startFrame",
    "endFrame",
    "fps",
    "appliedVisual",
    "bakedTrails",
    "trailIds",
    "bakedAttachments",
    "attachmentIds",
    "frameScales",
    "totalDurationMs",
    "bytes",
  ],
  xsxb_export_sheet: [
    "projectId",
    "profileId",
    "animationId",
    "outputPath",
    "frameCount",
    "startFrame",
    "endFrame",
    "indexes",
    "markFrame",
    "columns",
    "rows",
    "cell",
    "pad",
    "width",
    "height",
    "bytes",
    "bakedTrails",
    "trailIds",
    "bakedAttachments",
    "attachmentIds",
    "appliedVisual",
    "frameScales",
    "grid",
  ],
  xsxb_measure_image: [
    "filePath",
    "space",
    "note",
    "width",
    "height",
    "center",
    "pommel",
    "tip",
    "length",
    "direction",
    "directionSource",
    "t",
    "at",
    "localFromCenter",
    "fractions",
  ],
  xsxb_open_tuner: [
    "projectId",
    "profileId",
    "animationId",
    "url",
    "port",
    "rootHash",
    "conflictPort",
    "launched",
    "reused",
    "started",
    "pid",
  ],
});
const VISUAL_TOOLS = new Set([
  "xsxb_find_motion",
  "xsxb_estimate_boxes",
  "xsxb_add_attack_trail",
  "xsxb_plan_attachment",
  "xsxb_add_attachment",
  "xsxb_cutout",
  "xsxb_export_gif",
  "xsxb_export_sheet",
]);
const ARRAY_OUTPUT_FIELDS = new Set([
  "projects",
  "profiles",
  "animations",
  "preconditions",
  "steps",
  "completionChecks",
  "requiredCapabilities",
  "candidates",
  "suggestedOrder",
  "suggestedDrop",
  "dropIndexes",
  "drop",
  "order",
  "comparisons",
  "matches",
  "groups",
  "activity",
  "frames",
  "semanticFrames",
  "playbackUpdates",
  "updates",
  "sfx",
  "attachments",
  "trails",
  "sampleFrames",
  "sourceFxFrames",
  "warnings",
  "bindings",
  "backups",
  "removed",
  "revisions",
  "files",
  "includedAnimationIds",
  "availableAnimationIds",
  "errors",
  "nonBlockingWarnings",
  "frameScales",
  "trailIds",
  "attachmentIds",
  "indexes",
  "runtimeFiles",
]);
const BOOLEAN_OUTPUT_FIELDS = new Set([
  "created",
  "dryRun",
  "active",
  "godotProjectValid",
  "allFramesGenerated",
  "summary",
  "applied",
  "oneShotLikely",
  "analysisReliable",
  "semanticCacheReused",
  "replace",
  "identityOrder",
  "replaced",
  "sizeChanged",
  "deleted",
  "requiresVisualReview",
  "syncPending",
  "requested",
  "ok",
  "strict",
  "gameplayReady",
  "canAutoApplyWithoutVision",
  "rematched",
  "keyed",
  "boxesStale",
  "bakedTrails",
  "bakedAttachments",
  "appliedVisual",
  "launched",
  "reused",
  "started",
]);
const NUMBER_OUTPUT_FIELDS = new Set([
  "count",
  "profileCount",
  "animationCount",
  "frameCount",
  "fps",
  "extractedFrameCount",
  "importedFrameCount",
  "importedAnimationCount",
  "sourceFrameCount",
  "startFrame",
  "endFrame",
  "generatedFrameCount",
  "sampleSize",
  "rawStart",
  "rawEnd",
  "start",
  "end",
  "paddingBefore",
  "paddingAfter",
  "opaqueRatio",
  "updatedFrames",
  "frame",
  "estimatedFrames",
  "skippedExistingFrames",
  "attachmentHitboxFrames",
  "targetHeight",
  "nativeHeight",
  "groupScale",
  "zoomRatio",
  "zoomFrameCount",
  "inputFrameCount",
  "outputFrameCount",
  "frameSpan",
  "centerTravel",
  "edgeTravel",
  "derivedStickCount",
  "bladeWidthScale",
  "sourceFxOverlapRatio",
  "gripErrorPx",
  "tipAngleErrorDeg",
  "bindingCount",
  "removedCount",
  "remainingCount",
  "removedFrames",
  "restoredFiles",
  "copiedFrames",
  "prunedFrameFiles",
  "audioCount",
  "copiedAudio",
  "imageAttachmentCount",
  "copiedImageAttachments",
  "attackTrailCount",
  "copiedAttackTrailTextures",
  "processedFrameCount",
  "skippedFrameCount",
  "staleBoxFrameCount",
  "boxesReestimated",
  "outputWidth",
  "outputHeight",
  "totalDurationMs",
  "bytes",
  "markFrame",
  "columns",
  "rows",
  "cell",
  "pad",
  "width",
  "height",
  "length",
  "t",
  "port",
  "pid",
]);

function outputProperty(name, toolName) {
  if (name === "summary" && toolName === "xsxb_validate_project") return { type: "object" };
  if (name === "sourceAttachmentId") return { type: ["string", "null"] };
  if (name === "frame" || name === "pid") return { type: ["number", "null"] };
  if (ARRAY_OUTPUT_FIELDS.has(name)) return { type: "array" };
  if (BOOLEAN_OUTPUT_FIELDS.has(name)) return { type: "boolean" };
  if (NUMBER_OUTPUT_FIELDS.has(name)) return { type: "number" };
  if (/^(projectId|profileId|animationId|.*Path|.*Id|status|source|workflow|fallback)$/u.test(name)) {
    return { type: "string" };
  }
  return {};
}

function toolDefinitions() {
  const projectProperty = {
    type: "string",
    description: "XSXB project id. Defaults to the last selected/imported project.",
  };
  const animationProperties = {
    project_id: projectProperty,
    profile_id: { type: "string", description: "Animation profile id." },
    animation_id: { type: "string", description: "Animation id." },
  };
  const boxPointSchema = {
    type: "object",
    properties: {
      x: { type: "number" },
      y: { type: "number" },
    },
    additionalProperties: false,
  };
  const boxPatchSchema = {
    type: "object",
    properties: {
      enabled: { type: "boolean" },
      offset: boxPointSchema,
      size: {
        type: "object",
        properties: {
          x: { type: "number", minimum: 0 },
          y: { type: "number", minimum: 0 },
        },
        additionalProperties: false,
      },
      rotation: { type: "number" },
    },
    additionalProperties: false,
  };
  const frameBoxPatchSchema = {
    type: "object",
    required: ["frame"],
    properties: {
      frame: { type: "integer", minimum: 0 },
      hurtbox: boxPatchSchema,
      collisionbox: boxPatchSchema,
      hitbox: boxPatchSchema,
    },
    additionalProperties: false,
  };
  const definitions = [
    {
      name: "xsxb_list_projects",
      description: "List every local XSXB project, its active state, Godot binding, and animation counts.",
      inputSchema: { type: "object", properties: {}, additionalProperties: false },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_create_project",
      description:
        "Create and activate an empty local XSXB project. A Godot root is optional and can be bound later. Use dry_run to preview the stable id without writing.",
      inputSchema: {
        type: "object",
        properties: {
          id: { type: "string", description: "Preferred stable project id." },
          label: { type: "string", description: "Human-readable project label." },
          kind: { type: "string", default: "godot" },
          project_root: { type: "string", description: "Optional existing project directory." },
          dry_run: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
    },
    {
      name: "xsxb_get_project",
      description:
        "Return one project's registry record, Godot binding, animation list, frame counts, and last sync receipt.",
      inputSchema: {
        type: "object",
        properties: { project_id: projectProperty },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_get_workflow",
      description:
        "Return an on-demand XSXB production workflow with preconditions, ordered tools, completion checks, and mandatory failure feedback.",
      inputSchema: {
        type: "object",
        required: ["workflow"],
        properties: {
          workflow: { type: "string", enum: WORKFLOW_NAMES },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_import_video",
      description:
        "Extract every native frame from a local video, import it as an XSXB animation, optionally sync to Godot, and validate the result.",
      inputSchema: {
        type: "object",
        required: ["file_path"],
        properties: {
          file_path: { type: "string", description: "Absolute local video path." },
          fps: { type: "number", minimum: 1, maximum: 120, default: 12 },
          start_frame: {
            type: "integer",
            minimum: 0,
            description: "Inclusive 0-based extracted frame index.",
          },
          end_frame: { type: "integer", minimum: 0, description: "Inclusive 0-based extracted frame index." },
          replace: {
            type: "boolean",
            default: false,
            description: "Replace an existing animation id atomically.",
          },
          sync: { type: "boolean", default: false },
          validate: { type: "boolean", default: false },
          project_id: projectProperty,
          profile_id: { type: "string", default: DEFAULT_PROFILE_ID },
          animation_id: { type: "string", description: "Defaults to a sanitized video filename." },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
    },
    {
      name: "xsxb_import_animation",
      description:
        "Import a video, PNG sequence, SpriteFrames file, or PNG data items as an XSXB animation. Video import remains available as xsxb_import_video.",
      inputSchema: {
        type: "object",
        properties: {
          source: {
            type: "string",
            enum: ["video", "png_sequence", "spriteframes", "items"],
            description: "Import kind. Inferred from file_path, directory, or items when omitted.",
          },
          file_path: { type: "string", description: "Absolute video or .spriteframes.tres path." },
          directory: { type: "string", description: "Absolute directory of PNG frames." },
          items: {
            type: "array",
            items: { type: "object" },
            description: "PNG data-URL items for source=items.",
          },
          fps: { type: "number", minimum: 1, maximum: 120, default: 12 },
          start_frame: { type: "integer", minimum: 0 },
          end_frame: { type: "integer", minimum: 0 },
          replace: { type: "boolean", default: false },
          sync: { type: "boolean", default: false },
          validate: { type: "boolean", default: false },
          project_id: projectProperty,
          profile_id: { type: "string", default: DEFAULT_PROFILE_ID },
          animation_id: { type: "string" },
          animation_name: { type: "string" },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
    },
    {
      name: "xsxb_get_animation",
      description:
        "Return animation metadata and frames. Pass frames=summary for a compact sample without animation.frames. Pass include to also read back current boxes, timing, sfx, attachments, or trails.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          frames: { type: "string", enum: ["summary", "full"], default: "full" },
          include: {
            type: "array",
            items: {
              type: "string",
              enum: ["boxes", "timing", "visual", "sfx", "attachments", "trails"],
            },
            description:
              "Extra sections to return: box overrides, playback timing, visual transforms, and bindings.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_find_loop",
      description:
        "Rank loop-segment candidates with the same Tuner loop finder. Query an imported animation, a PNG directory, or file_paths. Does not mutate frames; apply a candidate with xsxb_reorganize_frames order. oneShotLikely is set when the recommended loop covers less than half of a clip with 12+ frames — inspect sheets or use xsxb_find_motion instead of applying a burst.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          directory: {
            type: "string",
            description: "Absolute PNG sequence directory. Overrides the imported animation when set.",
          },
          file_paths: {
            type: "array",
            items: { type: "string" },
            description:
              "Absolute PNG paths in playback order. Overrides directory and the imported animation when set.",
          },
          min_period: {
            type: "integer",
            minimum: 2,
            description: "Smallest loop period to consider. Defaults to the Tuner minimum of 2.",
          },
          max_period: {
            type: "integer",
            minimum: 2,
            description: "Largest loop period to consider. Defaults to two-thirds of the frame count.",
          },
          start_frame: {
            type: "integer",
            minimum: 0,
            description: "Ignore candidates that start before this 0-based index.",
          },
          preference: {
            type: "string",
            enum: ["auto", "short", "long"],
            default: "auto",
            description: "Bias ranking toward shorter or longer periods without dropping valid ones.",
          },
          boundary_factor: {
            type: "number",
            minimum: 0,
            maximum: 1,
            default: 0.85,
            description: "Same Tuner seam threshold as the organizer loop search.",
          },
          sample_size: {
            type: "integer",
            minimum: 8,
            maximum: 256,
            default: 256,
            description: "Square analysis sample. Matches the Tuner 256×256 reference size.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_find_duplicates",
      description:
        "Find near-duplicate hold frames with the same Tuner duplicate finder. Pass threshold or duplicate_ratio for the organizer 重复比例 slider; do not pass both unless they match. If autoAdjustedThreshold is set, do not apply order unless you passed auto_adjust. Query an imported animation, a PNG directory, or file_paths. Does not mutate frames; apply the keep-order with xsxb_reorganize_frames.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          directory: {
            type: "string",
            description: "Absolute PNG sequence directory. Overrides the imported animation when set.",
          },
          file_paths: {
            type: "array",
            items: { type: "string" },
            description:
              "Absolute PNG paths in playback order. Overrides directory and the imported animation when set.",
          },
          threshold: {
            type: "number",
            minimum: ORGANIZER_SIMILARITY_THRESHOLD.min,
            maximum: ORGANIZER_SIMILARITY_THRESHOLD.max,
            default: ORGANIZER_SIMILARITY_THRESHOLD.fallback,
            description: "Organizer 相似度阈值 / 重复比例 slider. Higher keeps more near-duplicates.",
          },
          duplicate_ratio: {
            type: "number",
            minimum: ORGANIZER_SIMILARITY_THRESHOLD.min,
            maximum: ORGANIZER_SIMILARITY_THRESHOLD.max,
            default: ORGANIZER_SIMILARITY_THRESHOLD.fallback,
            description: "Alias of threshold. Same organizer 重复比例 slider.",
          },
          auto_adjust: {
            type: "boolean",
            default: false,
            description:
              "If true, apply the finder's lowered threshold when nothing matches the requested slider. Default keeps order unchanged and reports autoAdjustedThreshold / suggestedOrder.",
          },
          sample_size: {
            type: "integer",
            minimum: 8,
            maximum: 256,
            default: 256,
            description: "Square analysis sample. Matches the Tuner 256×256 reference size.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_find_motion",
      description:
        "Find the interior motion window by trimming a leading rest hold and, when the clip returns to that rest, the trailing hold. Query an imported animation, a PNG directory, or file_paths. Does not mutate frames; apply the order with xsxb_reorganize_frames.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          directory: {
            type: "string",
            description: "Absolute PNG sequence directory. Overrides the imported animation when set.",
          },
          file_paths: {
            type: "array",
            items: { type: "string" },
            description:
              "Absolute PNG paths in playback order. Overrides directory and the imported animation when set.",
          },
          preset: {
            type: "string",
            enum: ["default", "attack"],
            default: "default",
            description:
              "attack keeps configurable anticipation and recovery padding around the raw motion peak.",
          },
          padding_before: { type: "integer", minimum: 0, maximum: 120 },
          padding_after: { type: "integer", minimum: 0, maximum: 120 },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_update_frame_boxes",
      description:
        "Update hurtbox, collisionbox, and hitbox for one animation frame, or many frames at once via frames. Does not sync Godot.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          frame: { type: "integer", minimum: 0, default: 0 },
          hurtbox: boxPatchSchema,
          collisionbox: boxPatchSchema,
          hitbox: boxPatchSchema,
          frames: {
            type: "array",
            items: frameBoxPatchSchema,
            description:
              "Batch mode: [{frame, hurtbox?, collisionbox?, hitbox?}, ...] applied in one write. Overrides the single-frame parameters.",
          },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_estimate_boxes",
      description:
        "Auto-estimate hurtbox, collisionbox, and hitbox overrides for every animation frame from opaque pixel bounds. Keeps existing overrides unless replace=true. Use dry_run to preview.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          replace: {
            type: "boolean",
            default: false,
            description: "Recompute frames that already have box overrides.",
          },
          dry_run: { type: "boolean", default: false },
          attachment_id: {
            type: "string",
            description:
              "Optional held weapon id; derives an oriented hitbox from grip to tip per attached frame.",
          },
          grip_t: { type: "number", minimum: 0, maximum: 1 },
          hitbox_width: { type: "number", exclusiveMinimum: 0 },
          hitbox_padding: { type: "number", minimum: 0, default: 4 },
          active_frames: {
            type: "array",
            items: { type: "integer", minimum: 0 },
            description: "Optional exact frames whose attachment-derived hitbox is enabled.",
          },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_update_timing",
      description:
        "Update animation FPS and optional per-frame duration or disabled playback, or many frames at once via frames. Does not sync Godot.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          fps: { type: "number", minimum: 1, maximum: 120 },
          frame: { type: "integer", minimum: 0 },
          duration_ms: { type: "number", minimum: 1 },
          duration: {
            type: "number",
            minimum: 0.001,
            description: "Frame duration multiplier. 1 equals one FPS tick.",
          },
          disabled: { type: "boolean" },
          frames: {
            type: "array",
            items: { type: "object" },
            description:
              "Batch mode: [{frame, duration_ms?, duration?, disabled?}, ...] applied in one write. Overrides the single-frame parameters.",
          },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_set_visual_transform",
      description:
        "Set visual size, offset, and rotation at the character (profile), animation group, or single-frame level. Pass clear=true to remove overrides at that level. Does not sync Godot.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          level: {
            type: "string",
            enum: ["character", "group", "frame"],
            default: "group",
            description:
              "character applies to the whole profile; group to one animation; frame to one frame.",
          },
          frame: { type: "integer", minimum: 0, description: "Required when level=frame." },
          visual_size: {
            type: "number",
            exclusiveMinimum: 0,
            description: "Uniform visual scale multiplier.",
          },
          offset_x: { type: "number" },
          offset_y: { type: "number" },
          rotation: { type: "number", description: "Rotation in radians." },
          clear: {
            type: "boolean",
            default: false,
            description: "Remove all visual overrides at the selected level.",
          },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_estimate_visual",
      description:
        "Estimate group and per-frame visual_size so standing height matches a reference animation or target_height. Frames shorter than the native median are treated as camera zoom-out; taller VFX or pose frames keep the group scale. apply writes those scales; bake pixels later with xsxb_cutout apply_visual.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          reference_animation_id: {
            type: "string",
            description:
              "Animation whose median standing height is the target when target_height is omitted.",
          },
          target_height: {
            type: "number",
            exclusiveMinimum: 0,
            description: "Desired standing body height in pixels. Overrides the reference median when set.",
          },
          zoom_ratio: {
            type: "number",
            minimum: 1,
            default: 1.12,
            description: "A frame shorter than native/zoom_ratio is treated as camera zoom-out.",
          },
          apply: {
            type: "boolean",
            default: false,
            description: "Write group and zoom-frame visual_size. Does not bake pixels.",
          },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_reorganize_frames",
      description:
        "Atomically reorganize animation frames and remap frame-owned tuning, audio, attachment, and attack-trail state. Defaults to an identity organization test.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          order: {
            type: "array",
            items: { type: "integer", minimum: 0 },
            description: "Source frame indexes in the desired output order. Defaults to the current order.",
          },
          sync: { type: "boolean", default: true },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_replace_frame",
      description:
        "Replace one workspace frame PNG with a new local PNG while keeping boxes, timing, and bindings. Updates the stored frame size when it changes.",
      inputSchema: {
        type: "object",
        required: ["frame", "file_path"],
        properties: {
          ...animationProperties,
          frame: { type: "integer", minimum: 0 },
          file_path: { type: "string", description: "Absolute replacement PNG path." },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
    },
    {
      name: "xsxb_add_attack_trail",
      description:
        "Add or replace one attack-trail segment. Sticks are blade edges (top=tip, bottom=grip) on one swing: start frame when the blade starts moving, end frame at the hit, a mid stick only if the arc bends. layer is behind while the blade is behind the body and front when it is in front. reverseDirection flips the curve handle if the ribbon folds through the body. Path length follows the faster blade edge, so a rotating slash still makes a trailing smear. Auto sticks start at the first frame and end at the last. before_stop_chase defaults to 0.12 so a slash-plus-settle still keeps the slash (拖影); 0 fills the whole swing; 1 hugs the current blade. Receipts include frameSpan, centerTravel, edgeTravel. xsxb_export_gif and xsxb_export_sheet bake the smear onto the preview. Omitting sticks writes a default two-stick trail.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          id: { type: "string", description: "Segment id. Defaults to the texture basename or trail." },
          name: { type: "string" },
          color: { type: "string", description: "#RRGGBB solid color." },
          color_mode: { type: "string", enum: ["solid", "original", "gradient"], default: "solid" },
          texture_path: {
            type: "string",
            description: "Absolute PNG trail texture. Defaults to the built-in luma preset.",
          },
          start_frame: { type: "integer", minimum: 0 },
          end_frame: { type: "integer", minimum: 0 },
          attachment_id: {
            type: "string",
            description:
              "Derive sticks from matching per-frame weapon attachments. Cannot be combined with sticks.",
          },
          grip_t: {
            type: "number",
            minimum: 0,
            maximum: 1,
            description: "Weapon grip fraction. Defaults to the confirmed attachment plan value.",
          },
          pommel_hint: {
            type: "object",
            required: ["x", "y"],
            properties: { x: { type: "number" }, y: { type: "number" } },
            additionalProperties: false,
          },
          tip_hint: {
            type: "object",
            required: ["x", "y"],
            properties: { x: { type: "number" }, y: { type: "number" } },
            additionalProperties: false,
          },
          flip_axis: { type: "boolean", default: false },
          opacity: {
            type: "number",
            minimum: 0,
            maximum: 1,
            default: 1,
            description: "Trail alpha multiplier shared by Tuner previews, exports, and Godot.",
          },
          blade_width_scale: {
            type: "number",
            minimum: 0.1,
            maximum: 2,
            default: 1,
            description: "Scale derived grip-to-tip stick width around its center.",
          },
          detect_source_fx: {
            type: "boolean",
            default: true,
            description:
              "Warn when bright source pixels near the weapon suggest an already-baked slash effect.",
          },
          source_fx_threshold: {
            type: "number",
            minimum: 0,
            maximum: 1,
            default: 0.03,
            description: "Highlighted sample ratio that triggers the baked-FX warning.",
          },
          dry_run: {
            type: "boolean",
            default: false,
            description:
              "Return the normalized trail, derived sticks, and FX warnings without writing project data.",
          },
          before_stop_chase: {
            type: "number",
            minimum: 0,
            maximum: 1,
            default: 0.12,
            description:
              "0.12 keeps a long smear so a follow-through does not erase the slash. 0 fills the whole swing. 1 hugs the current blade.",
          },
          after_stop_chase: {
            type: "number",
            minimum: 0.1,
            maximum: 20,
            default: 2,
            description: "How fast the tail catches the head after the last stick.",
          },
          sticks: {
            type: "array",
            description: "Blade-edge sticks. One swing per segment.",
            items: {
              type: "object",
              properties: {
                frame: { type: "integer", minimum: 0 },
                top: { type: "object", description: "Blade tip in group coordinates." },
                bottom: { type: "object", description: "Blade grip in group coordinates." },
                layer: {
                  type: "string",
                  enum: ["behind", "front"],
                  description: "Draw this stick's mesh behind or in front of the character.",
                },
                reverseDirection: {
                  type: "boolean",
                  description: "Flip the curve handle. Use when the ribbon folds through the body.",
                },
                tangentStrength: {
                  type: "number",
                  description: "Curve handle length. Product default 0.8; omit unless editing in Tuner.",
                },
              },
            },
          },
          sync: { type: "boolean", default: true },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_plan_attachment",
      description:
        "Plan a revision-bound weapon attachment from explicit hand and tip anchors, render a marked contact-sheet preview, and return a plan for confirmed xsxb_add_attachment application. Does not mutate project JSON.",
      inputSchema: {
        type: "object",
        required: ["file_path"],
        properties: {
          ...animationProperties,
          file_path: { type: "string", description: "Absolute weapon PNG path." },
          kind: { type: "string", enum: ["weapon", "effect"], default: "weapon" },
          id: { type: "string", description: "Logical attachment id." },
          name: { type: "string" },
          grip_t: {
            type: "number",
            minimum: 0,
            maximum: 1,
            description: "Grip fraction on the measured pommel-to-tip axis.",
          },
          pommel_hint: {
            type: "object",
            required: ["x", "y"],
            properties: { x: { type: "number" }, y: { type: "number" } },
            additionalProperties: false,
          },
          tip_hint: {
            type: "object",
            required: ["x", "y"],
            properties: { x: { type: "number" }, y: { type: "number" } },
            additionalProperties: false,
          },
          flip_axis: { type: "boolean", default: false },
          anchors: {
            type: "array",
            items: {
              type: "object",
              required: ["frame", "hand"],
              properties: {
                frame: { type: "integer", minimum: 0 },
                hand: {
                  type: "object",
                  required: ["x", "y"],
                  properties: { x: { type: "number" }, y: { type: "number" } },
                  additionalProperties: false,
                },
                tip: {
                  type: "object",
                  required: ["x", "y"],
                  properties: { x: { type: "number" }, y: { type: "number" } },
                  additionalProperties: false,
                },
                rotation: { type: "number" },
                scale: { type: "number", exclusiveMinimum: 0 },
                layer: { type: "string", enum: ["above", "below"], default: "above" },
              },
              additionalProperties: false,
            },
          },
          start_frame: { type: "integer", minimum: 0 },
          end_frame: { type: "integer", minimum: 0 },
          preview_path: {
            type: "string",
            description:
              "Optional PNG path inside the selected project workspace; protected asset paths are denied.",
          },
          response_mode: {
            type: "string",
            enum: ["full", "compact"],
            default: "full",
            description: "compact returns plan identity and summary; apply it later with plan_id.",
          },
          apply_mode: {
            type: "string",
            enum: ["create", "replace"],
            default: "create",
            description:
              "create refuses existing target instances; replace atomically swaps every planned instance.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_add_attachment",
      description:
        "Bind a local PNG as a frame image attachment. file_path is required for a real asset. Pass frames to bind the same asset on many frames in one write.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          file_path: { type: "string", description: "Absolute PNG path to attach." },
          frame: { type: "integer", minimum: 0, default: 0 },
          frames: {
            type: "array",
            items: { type: "object" },
            description:
              "Batch mode: [{frame, offset_x?, offset_y?, scale?, rotation?}, ...] applied in one write. Shared file_path/id/layer apply to every entry. Overrides the single-frame parameters.",
          },
          id: { type: "string" },
          name: { type: "string" },
          layer: { type: "string", enum: ["above", "below"], default: "above" },
          layer_order: { type: "integer", default: 1 },
          offset_x: { type: "number", default: 0 },
          offset_y: { type: "number" },
          scale: { type: "number", default: 1 },
          rotation: { type: "number", default: 0 },
          plan: {
            type: "object",
            description: "Plan returned by xsxb_plan_attachment. Requires confirm=true.",
          },
          plan_id: {
            type: "string",
            description: "Immutable server-reviewed plan id returned by xsxb_plan_attachment compact mode.",
          },
          review_confirmation: {
            type: "object",
            required: ["artifact_id", "mode", "decision"],
            properties: {
              artifact_id: { type: "string" },
              mode: { type: "string", enum: ["multimodal", "human"] },
              decision: { type: "string", enum: ["approve"] },
              notes: { type: "string" },
            },
            additionalProperties: false,
          },
          receipt_mode: {
            type: "string",
            enum: ["compact", "full"],
            description: "plan_id defaults to compact; full includes every persisted binding.",
          },
          confirm: { type: "boolean", default: false },
          sync: { type: "boolean", default: true },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_add_sfx",
      description: "Bind a local WAV/OGG/MP3 to one animation frame. file_path is required for a real clip.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          file_path: { type: "string", description: "Absolute audio path." },
          frame: { type: "integer", minimum: 0, default: 0 },
          id: { type: "string" },
          name: { type: "string" },
          sync: { type: "boolean", default: true },
        },
        required: ["file_path"],
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_remove_binding",
      description:
        "Remove one SFX, attachment, or attack-trail binding by id from one animation. Use frame to disambiguate sfx/attachment bindings that share an id. Supports dry_run.",
      inputSchema: {
        type: "object",
        required: ["kind", "id"],
        properties: {
          ...animationProperties,
          kind: { type: "string", enum: ["sfx", "attachment", "trail"] },
          id: { type: "string", description: "Binding or trail segment id." },
          frame: {
            type: "integer",
            minimum: 0,
            description: "Only remove the binding on this frame. Not applicable to trails.",
          },
          dry_run: { type: "boolean", default: false },
          sync: { type: "boolean", default: true },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false },
    },
    {
      name: "xsxb_delete_animation",
      description:
        "Delete one imported animation and its owned frames, tuning, and bindings. Supports dry_run.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          dry_run: { type: "boolean", default: false },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false },
    },
    {
      name: "xsxb_list_project_revisions",
      description: "List retained MCP mutation revisions and their restore scope for one project.",
      inputSchema: {
        type: "object",
        properties: {
          project_id: projectProperty,
          limit: { type: "integer", minimum: 1, maximum: 100, default: 20 },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_restore_project_revision",
      description:
        "Preview or restore one retained MCP mutation revision. Run dry_run first and replay its restore_token with confirm=true.",
      inputSchema: {
        type: "object",
        required: ["revision_id"],
        properties: {
          project_id: projectProperty,
          revision_id: { type: "string" },
          dry_run: { type: "boolean", default: false },
          restore_token: { type: "string" },
          confirm: { type: "boolean", default: false },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false },
    },
    {
      name: "xsxb_sync_godot",
      description: "Synchronize the current project to its bound Godot root without changing animation data.",
      inputSchema: {
        type: "object",
        properties: {
          project_id: projectProperty,
          force: { type: "boolean", default: false },
          dry_run: { type: "boolean", default: false },
          include_animation_ids: {
            type: "array",
            items: { type: "string" },
            description: "Optional animation ids to deliver; omitted means the complete project.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_validate_project",
      description:
        "Validate standalone XSXB data, generated frames, Godot-synchronized data, assets, and runtime files.",
      inputSchema: {
        type: "object",
        properties: {
          project_id: projectProperty,
          strict: { type: "boolean", default: false },
          require_gameplay: { type: "boolean", default: false },
          layer: {
            type: "string",
            enum: ["all", "standalone", "bind", "gameplay"],
            default: "all",
            description: "Report only one validation layer. Default all, bind errors listed first.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_set_active_project",
      description: "Set the registry active XSXB project used when project_id is omitted.",
      inputSchema: {
        type: "object",
        required: ["project_id"],
        properties: { project_id: projectProperty },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_bind_godot",
      description:
        "Point one XSXB project at an existing Godot root that contains project.godot. Does not sync files.",
      inputSchema: {
        type: "object",
        required: ["project_root"],
        properties: {
          project_id: projectProperty,
          project_root: { type: "string", description: "Absolute Godot project directory." },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_cutout",
      description:
        "Run the tuner smart-cutout product path on every animation frame. Slider names and ranges match the cutout workbench; omit them to keep the shared smart-cutout profile. Omitting the canvas keeps the source layout; an explicit canvas shares one scale and pins body feet to the bottom. apply_visual rematches from group/frame visual_size instead of that shared scale. Character visual_size stays playback-only and is not baked.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          key_color: {
            type: "string",
            description: "Optional #RRGGBB key. Omit to auto-detect the same background as the tuner.",
          },
          output_width: {
            type: "integer",
            minimum: 8,
            maximum: 4096,
            description: "Optional canvas width. Omit to keep each frame's source size.",
          },
          output_height: {
            type: "integer",
            minimum: 8,
            maximum: 4096,
            description: "Optional canvas height. Defaults to output_width when only width is set.",
          },
          protected_colors: {
            type: "array",
            items: { type: "string" },
            description: "Optional #RRGGBB colors to keep, same as the tuner protect-color list.",
          },
          ...workbenchSliderSchemaProperties(),
          force: {
            type: "boolean",
            default: false,
            description: "Re-cut frames whose borders are already transparent.",
          },
          apply_visual: {
            type: "boolean",
            default: false,
            description:
              "Rematch using group/frame visual_size instead of one shared scale. Requires or infers a canvas. Character visual_size is not baked.",
          },
          metrics: {
            type: "boolean",
            default: true,
            description:
              "Include per-frame bodyHeight, feetY, and leftover near-white counts on the receipt.",
          },
          reestimate_boxes: {
            type: "boolean",
            default: false,
            description: "Replace frame boxes from the post-cutout alpha bounds in the same MCP operation.",
          },
          sync: { type: "boolean", default: false },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false },
    },
    {
      name: "xsxb_export_gif",
      description:
        "Export one animation as an animated GIF preview via FFmpeg, including workbench attachments and attack trails by default and honoring timing plus group/frame visual_size. Skips disabled frames.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          output_path: {
            type: "string",
            description:
              "Relative or absolute .gif destination inside the selected project workspace. Relative paths keep legacy workspace anchoring.",
          },
          fps: { type: "number", minimum: 1, maximum: 120, description: "Defaults to the animation FPS." },
          start_frame: { type: "integer", minimum: 0, description: "Inclusive 0-based frame index." },
          end_frame: { type: "integer", minimum: 0, description: "Inclusive 0-based frame index." },
          include_disabled: {
            type: "boolean",
            default: false,
            description: "Also render frames whose playback is disabled.",
          },
          include_attachments: {
            type: "boolean",
            default: true,
            description: "Composite frame image attachments in workbench layer order.",
          },
          include_trails: {
            type: "boolean",
            default: true,
            description: "Composite authored attack trails.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_export_sheet",
      description:
        "Export a contact sheet PNG with workbench attachments and attack trails by default. Shared cells keep standing size and leftover dirt comparable; labels and the group grid use foot origin 0,0 with the body in negative y.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          output_path: {
            type: "string",
            description:
              "Relative or absolute .png destination inside the selected project workspace. Relative paths keep legacy workspace anchoring.",
          },
          start_frame: { type: "integer", minimum: 0, description: "Inclusive 0-based frame index." },
          end_frame: { type: "integer", minimum: 0, description: "Inclusive 0-based frame index." },
          include_attachments: {
            type: "boolean",
            default: true,
            description: "Composite frame image attachments in workbench layer order.",
          },
          include_trails: {
            type: "boolean",
            default: true,
            description: "Composite authored attack trails.",
          },
          mark_frame: {
            type: "integer",
            minimum: 0,
            description:
              "Absolute 0-based frame to highlight. Defaults to start_frame so the loop start is marked.",
          },
          columns: {
            type: "integer",
            minimum: 1,
            maximum: 32,
            description: "Cells per row. Defaults to min(frameCount, 8).",
          },
          cell: {
            type: "integer",
            minimum: 8,
            maximum: 1024,
            default: 220,
            description: "Shared cell edge in pixels. Every source canvas is scaled into this cell.",
          },
          pad: { type: "integer", minimum: 1, maximum: 64, default: 8 },
          grid: {
            type: "boolean",
            default: true,
            description: "Paint the tuner group-coordinate axes and ticks. Origin is the canvas foot.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_measure_image",
      description:
        "Measure a PNG's long axis. The pommel is the end closer to the widest cross-section and the far end is the tip. Pass t for a grip fraction. Returns image-pixel landmarks for xsxb_plan_attachment. Manual placement must rotate and scale localFromCenter before subtracting it from the hand point.",
      inputSchema: {
        type: "object",
        required: ["file_path"],
        properties: {
          file_path: { type: "string", description: "Absolute PNG path of the weapon or sprite." },
          t: {
            type: "number",
            minimum: 0,
            maximum: 1,
            default: 0.5,
            description: "Grip fraction along pommel→tip. 0.5 is the middle; send 0.666… or the string 2/3.",
          },
          pommel_hint: {
            type: "object",
            required: ["x", "y"],
            properties: { x: { type: "number" }, y: { type: "number" } },
            additionalProperties: false,
          },
          tip_hint: {
            type: "object",
            required: ["x", "y"],
            properties: { x: { type: "number" }, y: { type: "number" } },
            additionalProperties: false,
          },
          flip_axis: {
            type: "boolean",
            default: false,
            description: "Reverse the measured pommel-to-tip direction after hints/heuristics.",
          },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    },
    {
      name: "xsxb_open_tuner",
      description:
        "Start the local Tuner if needed and return a workspace URL focused on one project, profile, and animation.",
      inputSchema: {
        type: "object",
        properties: {
          ...animationProperties,
          start: {
            type: "boolean",
            default: true,
            description: "Start the Tuner process when it is not listening.",
          },
          port: { type: "integer", minimum: 1, maximum: 65535, default: 5179 },
        },
        additionalProperties: false,
      },
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
    },
  ];
  return definitions.map((definition) => ({
    ...definition,
    title:
      definition.title ||
      definition.name
        .replace(/^xsxb_/u, "XSXB ")
        .split("_")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(" "),
    outputSchema:
      definition.outputSchema ||
      (() => {
        const primary = OUTPUT_PRIMARY_FIELDS[definition.name];
        const fields = [...new Set([...COMMON_OUTPUT_FIELDS, ...(OUTPUT_FIELDS[definition.name] || [])])];
        return {
          type: "object",
          properties: Object.fromEntries(
            fields.map((field) => [
              field,
              primary?.[0] === field ? { type: primary[1] } : outputProperty(field, definition.name),
            ]),
          ),
          required: primary ? [primary[0]] : [],
          additionalProperties: false,
        };
      })(),
    execution: { taskSupport: "forbidden" },
    _meta: VISUAL_TOOLS.has(definition.name)
      ? {
          "xsxb/reviewPolicy": {
            requiredCapabilities: ["image_input"],
            fallback: "human_review",
            canAutoApplyWithoutVision: false,
          },
        }
      : undefined,
    annotations: {
      readOnlyHint: false,
      destructiveHint: true,
      idempotentHint: false,
      ...definition.annotations,
      openWorldHint: false,
    },
  }));
}

const MCP_TOOL_NAMES = Object.freeze(toolDefinitions().map((tool) => tool.name));

module.exports = { DEFAULT_PROFILE_ID, MCP_TOOL_NAMES, toolDefinitions };
